name: 🐛 Bug Report
description: Report an issue with the documentation (broken links, incorrect information, etc.)
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - dodopayments/documentation-team

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a documentation issue! Please fill out the form below to help us fix it quickly.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please provide a clear and concise description of the issue
      placeholder: |
        Example: The API endpoint for creating payments shows incorrect parameters...
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL
      description: The URL of the documentation page with the issue
      placeholder: https://docs.dodopayments.com/api-reference/payments
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of Issue
      description: What kind of issue are you reporting?
      options:
        - Incorrect information
        - Broken link
        - Missing information
        - Code example not working
        - Formatting/display issue
        - Image not loading
        - Navigation issue
        - Search not finding content
        - Other
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Content/Behavior
      description: What should the documentation show or how should it behave?
      placeholder: The parameter should be named 'customer_id' not 'customerId'
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Content/Behavior
      description: What does the documentation currently show or how does it behave?
      placeholder: The documentation shows 'customerId' as the parameter name
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue
      placeholder: Drag and drop images here

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - 🚨 Critical (blocks usage)
        - 🔴 High (significantly impacts understanding)
        - 🟡 Medium (causes confusion)
        - 🟢 Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: This affects all payment integration examples...